//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lavka.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public Services()
        {
            this.Posts = new HashSet<Posts>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<int> IdDirections { get; set; }
    
        public virtual Directions Directions { get; set; }
        public virtual ICollection<Posts> Posts { get; set; }
    }
}
